# models
model_name_SED: "BEATs" # Options: ["BEATs", "ATST-F", "fpasst", "M2D", "ASIT"]
model_name_Text: "HuggingFaceTB/SmolLM2-360M-Instruct" 
# Options: ["HuggingFaceTB/SmolLM2-135M-Instruct", "HuggingFaceTB/SmolLM2-360M-Instruct", 
#           "Qwen/Qwen2.5-0.5B-Instruct", "Qwen/Qwen2.5-1.5B-Instruct", "HuggingFaceTB/SmolLM2-1.7B-Instruct"]

# text style
style: "flat" # Options: [flat, temporal, scene, cot]

# audio parameters
sample_rate: 16000
clip_duration: 10.0

# path
path_meta: "/work/u5049807/AudioSet-Strong/metadata"
path_audio: "/work/u5049807/AudioSet-Strong/audio"
train_file: "audioset_train_strong.tsv"
eval_file: "audioset_eval_strong.tsv"
mid2name_file: "mid_to_display_name.tsv"

result_dir: 'prediction_results'


# dataloader
batch_size: 128
num_workers: 4
